export const SUCCESS_GET_DATA_QURAN = "SUCCESS_GET_DATA_QURAN";
export const PROCESS_GET_DATA_QURAN = "PROCESS_GET_DATA_QURAN";
export const FAILED_GET_DATA_QURAN = "FAILED_GET_DATA_QURAN";

export const GET_DATA_CHAPTER = "GET_DATA_CHAPTER";